-- CREATING USER LOGIN TABLE
CREATE TABLE user_exist (
        CARD_NO NUMBER(16) NOT NULL,
        USER_NAME VARCHAR2(30)  NOT NULL,
        PIN NUMBER(4) NOT NULL,
        ADDRESS VARCHAR2(50),
        DATA_TIME VARCHAR2(10),
        PRIMARY KEY ( CARD_NO )
);

-- CREATING TRANSACTION TABLE
CREATE TABLE TRANSCATION_DETAILS (
        CARD_NO NUMBER(16) NOT NULL,
        OLD_AVAILABLE_BALANCE NUMBER(10),
        DEPOSIT  NUMBER(10),
        WITHDRAW    NUMBER(10),
        AVAILABLE_BALANCE  NUMBER(10),
        DATE_TIME   DATE
);
